// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZD_nmm3srp7Ozv7wYkO7irUiwDLKQC2g',
    appId: '1:65760144145:web:94cafbbd2f49a7b5cffab0',
    messagingSenderId: '65760144145',
    projectId: 'fir-chat-app-72c17',
    authDomain: 'fir-chat-app-72c17.firebaseapp.com',
    storageBucket: 'fir-chat-app-72c17.appspot.com',
    measurementId: 'G-5568GNSCD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmVrtXMtyCgNT1y_TveOQvMBXnfZ0hQoY',
    appId: '1:65760144145:android:8d9aa09b1cedd4c5cffab0',
    messagingSenderId: '65760144145',
    projectId: 'fir-chat-app-72c17',
    storageBucket: 'fir-chat-app-72c17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8a2RzqTTWXYXtRHfB4XOAC2SGUIkzOv0',
    appId: '1:65760144145:ios:11ddfafba94ca88dcffab0',
    messagingSenderId: '65760144145',
    projectId: 'fir-chat-app-72c17',
    storageBucket: 'fir-chat-app-72c17.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8a2RzqTTWXYXtRHfB4XOAC2SGUIkzOv0',
    appId: '1:65760144145:ios:11ddfafba94ca88dcffab0',
    messagingSenderId: '65760144145',
    projectId: 'fir-chat-app-72c17',
    storageBucket: 'fir-chat-app-72c17.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZD_nmm3srp7Ozv7wYkO7irUiwDLKQC2g',
    appId: '1:65760144145:web:b896cb383731cba2cffab0',
    messagingSenderId: '65760144145',
    projectId: 'fir-chat-app-72c17',
    authDomain: 'fir-chat-app-72c17.firebaseapp.com',
    storageBucket: 'fir-chat-app-72c17.appspot.com',
    measurementId: 'G-M9L40QJ7V1',
  );
}
